repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.6
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format

- repo: local
  hooks:
    - id: uv-export
      name: Update requirements.txt from uv.lock
      entry: uv export --format requirements-txt --output-file requirements.txt --no-hashes --quiet
      language: system
      files: ^uv\.lock$
      pass_filenames: false