[project]
name = "agentfactory"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "charset-normalizer>=3.4.1",
    "duckduckgo-search>=7.1.1",
    "dynaconf>=3.2.6",
    "griffe>=1.5.1",
    "httpx>=0.27.2",
    "jinja2>=3.1.4",
    "loguru>=0.7.2",
    "niquests>=3.11.4",
    "openai>=1.55.0",
    "pydantic>=2.10.0",
    "pyyaml>=6.0.2",
    "sqlmodel>=0.0.22",
    "tenacity>=9.0.0",
]

[dependency-groups]
dev = [
    "ruff>=0.8.0",
]
eval = [
    "datasets>=3.2.0",
    "nbformat>=5.10.4",
]

[tool.ruff]
exclude = ["eval"]

[tool.ruff.lint]
# 启用导入排序规则
select = ["I001"]
