[project]
name = "agentfactory"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "griffe>=1.5.1",
    "httpx>=0.27.2",
    "pydantic>=2.10.0",
    "pyyaml>=6.0.2",
    "tavily-python>=0.5.0",
]

[dependency-groups]
dev = [
    "ruff>=0.8.0",
]

[tool.ruff.lint]
# 启用导入排序规则
select = ["I001"]
