models:
  gpt-4o-mini:
    api_key: "sk-CG64tTiXHRTTmSvf0642Fa33A1Ba4b71B6E1287f0c6793A6"
    base_url: "https://toollearning.cn/v1/"
  gpt-4o:
    api_key: "sk-CG64tTiXHRTTmSvf0642Fa33A1Ba4b71B6E1287f0c6793A6"
    base_url: "https://toollearning.cn/v1/"
  deepseek-chat:
    api_key: "sk-CG64tTiXHRTTmSvf0642Fa33A1Ba4b71B6E1287f0c6793A6"
    base_url: "https://toollearning.cn/v1/"
    max_tokens: 4096
  
  # local models below  
  qwen2.5:latest:
    api_key: "dummy_api"
    base_url: "http://localhost:11434/v1/"
  qwen2.5:7b:
    api_key: "dummy_api"
    base_url: "http://localhost:11434/v1/"


# model configuration
default_model: gpt-4o-mini
temperature: 0.5
top_p: 1.0
frequency_penalty: 0.0
timeout: 60
max_retries: 5

# paths
prompt_folder_path: "/Users/logic/Documents/CodeSpace/AgentFactory/prompts"
logs_folder_path: "/Users/logic/Documents/CodeSpace/AgentFactory/logs"

# tools
search_api_endpoint: "http://localhost:8000/"

