# .github/workflows/run-repoagent.yml
name: Use RepoAgent Action

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
      
permissions:
  contents: write  # This action requires write permissions for contents to push changes to the repository.
  
jobs:
  use-repoagent:
    if: github.event.pull_request.merged == true  # Run only if the pull request is merged
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Run RepoAgent Action
        uses: Umpire2018/setup-repoagent@v1
        with:
          openai_base_url: "${{ secrets.OPENAI_BASE_URL }}"
          openai_api_key: "${{ secrets.OPENAI_API_KEY }}"
